[common]
#url = https://dev-pro.repairsolutions.innovavietnam.com/
urls = https://pro.repairsolutions.com/

[pytest]
addopts = --html=reports/General_Report.html --self-contained-html
testpaths = test_cases

markers =
    IntroductionFeatures : Test Case for Homepage module
    Diagnostic : Test Case for Homepage module
    MyReport : Test Cases for My Report module
    SignUp : Test Case for Authentication module
    Login : Test Case for Authentication module
    SignUpZipcode : Test Cases for Zipcode
    DTCLibrary : Test Case for DTC LookUp module
    SGW : Test Case for Security Gate Way of Diagnostic tables module
    SupportRequest : Test Case for Support Request page video link
    ProductSDS50 : Test Case for Product SDS50 tool page
    Product7111 : Test Case for Product 7111 tool page

[credentials]
email = sangqa@yopmail.com
password =123456789
